all: ImageMaker

ImageMaker:
	@echo
	@echo ================= Build Image Maker =================
	@echo
	
	make -C 00.ImageMaker
	
	@echo
	@echo ================= Build Complete =================
	@echo
	
	cp ./00.ImageMaker/ImageMaker ./../ImageMaker

clean:
	rm -C 00.ImageMaker